server:
  port: 7001
  servlet:
    context-path: /ad-search

spring:
  application:
    name: eureka-client-ad-search
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://192.168.159.4:3306/muke?autoReconnect=true
    username: root
    password: 123456
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2
  kafka:
    bootstrap-servers: 192.168.159.4:9092
    listener:
      concurrency: 4

eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/

feign:
  hystrix:
    enabled: true

# 监控信息
management:
  endpoints:
    web:
      exposure:
        #       暴露全部信息
        include: "*"

adconf:
  mysql:
    host: 192.168.159.4
    port: 3306
    username: root
    password: tangcj
    binlogName: binlog.000038
    position: -1

  kafka:
    topic: ad-search-mysql-data